version: "3"

services:
  irisnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris-node
    environment:
      - MONIKER=Irishub
      - CHAIN_ID=irishub
      - BOOTSTRAP=FALSE
      - IRIS_HOME=/.iris
      - SEEDS=6a6de770deaa4b8c061dffd82e9c7f4d40c2165d@seed-1.mainnet.irisnet.org:26656,a17d7923293203c64ba75723db4d5f28e642f469@seed-2.mainnet.irisnet.org:26656, 595cef3914b6dfe3846f7694892e3d1e32dadfbc@35.196.175.11:36656
      - PERSISTENT_PEERS=6a6de770deaa4b8c061dffd82e9c7f4d40c2165d@seed-1.mainnet.irisnet.org:26656,a17d7923293203c64ba75723db4d5f28e642f469@seed-2.mainnet.irisnet.org:26656, 595cef3914b6dfe3846f7694892e3d1e32dadfbc@35.196.175.11:36656
      - PROMETHEUS_LISTEN_ADDR=36660
      - MAX_OPEN_CONNECTIONS=10
      - LCD_PORT=3317
      - RPC_PORT=36657
      - P2P_PORT=36656
      - PROXY_APP_PORT=36658
      - SEND_RATE=4096
      - RECV_RATE=4096
    restart: always
    ports:
      - "36656:36656"
      - "36657:36657"
      - "36658:36658"
      - "3317:3317" # for rest-server
    volumes:
      - iris-data:/.iris
volumes:
  iris-data:
